name: GitHub Pages

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/cache@v3
        with:
            path: |
              .cpcache
              .shadow-cljs
              ~/.m2
            key: "1"

      - uses: actions/checkout@v3

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@4.0
        with:
          # Install just one or all simultaneously
          cli: 1.10.3.1087 # Clojure CLI based on tools.deps
          # (optional) To avoid rate limit errors please provide github token
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install babashka
        uses: just-sultanov/setup-babashka@v2
        with:
          version: '0.8.156'

      - name: Build static site
        run: bb publish-gh-pages

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
